name: Build and Test
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install native solc
        run: sudo apt-get update && sudo apt-get install -y solc

      - name: Verify solc version
        run: solc --version
        
      - name: Install solc globally
        run: npm install -g solc

      - name: Verify solc version
        run: npx solcjs --version

      - name: Run tests
        run: npm test
